# Generated by Django 3.1.7 on 2021-05-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagegallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('cover_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegallery.image')),
            ],
        ),
    ]
