# Generated by Django 3.2.4 on 2021-07-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagegallery', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('companyLogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegallery.image')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contactEmail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videoLink', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegallery.image')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerTitle', models.CharField(max_length=255)),
                ('headerDescription', models.TextField()),
                ('companies', models.ManyToManyField(to='homepage.Companies')),
                ('contactInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.contactinfo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.location')),
                ('ongoingProjects', models.ManyToManyField(related_name='ongoing_projects', to='projects.Project')),
                ('promotedProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_projects', to='projects.project')),
                ('services', models.ManyToManyField(to='homepage.Service')),
                ('videoSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.videosection')),
            ],
        ),
    ]
