# Generated by Django 3.1.7 on 2021-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosection',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='videoLink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
