# Generated by Django 3.1.7 on 2021-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210329_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='videoLink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
