# Generated by Django 3.1.7 on 2021-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210329_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
