# Generated by Django 3.1.7 on 2021-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210503_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitie',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='amenities',
            field=models.ManyToManyField(to='projects.Amenitie'),
        ),
    ]
