# Generated by Django 3.1.7 on 2021-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210503_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='sheet_url',
            field=models.FileField(upload_to='project_sheet_files/'),
        ),
    ]
