# Generated by Django 3.1.7 on 2021-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_infos',
            field=models.ManyToManyField(to='projects.ProjectInfo'),
        ),
    ]
