# Generated by Django 3.1.7 on 2021-05-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dimension',
            field=models.IntegerField(choices=[(1, '2D'), (2, '3D')], default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
