# Generated by Django 3.1.7 on 2021-05-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0002_auto_20210505_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.IntegerField(choices=[(1, 'Ongoing'), (2, 'Completed')], default=2),
        ),
    ]
