# Generated by Django 3.1.7 on 2021-05-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0003_auto_20210512_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
