# Generated by Django 3.1.7 on 2021-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagegallery', '0003_auto_20210329_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
